#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=48:00:00
#SBATCH --partition=acomputeq
#SBATCH --output=compressed.out

source ~/.bashrc
conda activate rinrus
qmdir=$(pwd)
SECONDS=0

date
echo "Compressing all *-maxcyc-out and *-optcrash-out, as well as orca.property.txt of finished jobs (based on check_[job]_done.txt lists)"
echo "Whole QM dir before compression: $(du -hs)"

for i in $(ls -d f*); do	# gets all fxxxxx-fxxxxx directories
 cd $i
 echo "$i before compression: $(du -hs)"
 # compress all maxcyc and optcrash output files 
 find . -type f -name *-maxcyc-out -exec gzip -v {} \; 
 find . -type f -name *-optcrash-out -exec gzip -v {} \;
 # if calc is done; compress orca.property.txt 
 for j in initialopt tsconstrained tsopt irc1 irc2; do
  if [ -f "check_${j}_done.txt" ]; then
   for d in $(cat check_${j}_done.txt); do
    if [ -f $d/orca.property.txt ]; then
     gzip -v $d/orca.property.txt
    fi
   done
  fi
 done
 echo "$i after compression: $(du -hs)"
 cd $qmdir
done

echo "Whole QM dir after compression: $(du -hs)"

if (( $SECONDS > 3600 )) ; then
    let "hours=SECONDS/3600"
    let "minutes=(SECONDS%3600)/60"
    let "seconds=(SECONDS%3600)%60"
    echo "Completed in $hours hour(s), $minutes minute(s) and $seconds second(s)"
elif (( $SECONDS > 60 )) ; then
    let "minutes=(SECONDS%3600)/60"
    let "seconds=(SECONDS%3600)%60"
    echo "Completed in $minutes minute(s) and $seconds second(s)"
else
    echo "Completed in $SECONDS seconds"
fi

