#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=48:00:00
#SBATCH --partition=acomputeq
#SBATCH --output=compressed.out

source ~/.bashrc
conda activate rinrus
qmdir=$(pwd)
SECONDS=0

date
echo "Deleting: all orca.property.txt, orca.densities, orca.densitiesinfo, orca.engrad, orca.bibtex files"
echo "Compressing: all *-maxcyc-out, *-optcrash-out, gbw, and xtbw files for finished jobs, as well as hess files for finished initialopt/irc jobs"
echo "Finished jobs determined based on check_[job]_done.txt lists"
echo "-----"
echo "Whole QM dir before cleanup: $(du -hs)"

for i in $(ls -d f*); do	# gets all fxxxxx-fxxxxx directories
 cd $i
 echo "$i before cleanup: $(du -hs)"
 # remove any densities/densitiesinfo/engrad/bibtex files and property files (original or compressed)
 find . \( -name "orca.densities" -o -name "orca.densitiesinfo" -o -name "orca.engrad" -o -name "orca.bibtex" \) -delete
 find . \( -name "orca.property.txt" -o -name "orca.property.txt.gz" \) -delete
 # if calc is done; compress stuff
 for j in initialopt tsconstrained tsopt irc1 irc2; do
  if [ -f "check_${j}_done.txt" ]; then
   for d in $(awk '{print $1}' check_${j}_done.txt); do
    # compress all maxcyc and optcrash output files 
    find $d/* -maxdepth 0 -type f -name *-maxcyc-out -exec gzip -v {} \;
    find $d/* -maxdepth 0 -type f -name *-optcrash-out -exec gzip -v {} \;
    # compress all gbw, xtbw files
    find $d/* -maxdepth 0 -type f -name *gbw -exec gzip -v {} \;
    find $d/* -maxdepth 0 -type f -name *xtbw -exec gzip -v {} \;
    # compress all hess and carthess files for initialopt and ircs
    if [[ "$j" == "initialopt" ]] || [[ "$j" == "irc1" ]] || [[ "$j" == "irc2" ]]; then
     find $d/* -maxdepth 0 -type f -name *.hess -exec gzip -v {} \;
     find $d/* -maxdepth 0 -type f -name *-hess -exec gzip -v {} \;
     find $d/* -maxdepth 0 -type f -name *.carthess -exec gzip -v {} \;
    fi
   done
  fi
 done
 echo "$i after cleanup: $(du -hs)"
 cd $qmdir
done

echo "Whole QM dir after cleanup: $(du -hs)"

if (( $SECONDS > 3600 )) ; then
    let "hours=SECONDS/3600"
    let "minutes=(SECONDS%3600)/60"
    let "seconds=(SECONDS%3600)%60"
    echo "Completed in $hours hour(s), $minutes minute(s) and $seconds second(s)"
elif (( $SECONDS > 60 )) ; then
    let "minutes=(SECONDS%3600)/60"
    let "seconds=(SECONDS%3600)%60"
    echo "Completed in $minutes minute(s) and $seconds second(s)"
else
    echo "Completed in $SECONDS seconds"
fi

