#!/bin/bash
#SBATCH --ntasks-per-node=20
#SBATCH --nodes=1
#SBATCH --partition=acomputeq
#SBATCH --time=100:00:00
#SBATCH --job-name=ORCAJOB
#SBATCH --output=ORCAJOB-%j.out
#SBATCH --error=ORCAJOB-%j.err
#SBATCH --mem=40GB

##### Specify name for input and output files #####
name=orca

#export orcadir=/home/ndyonker/src/orca_6_0_0
module load orca/6.1.1
export orcadir=/opt/ohpc/pub/apps/uofm/orca/6.1.1
echo $orcadir
export PATH=$orcadir:$PATH

 
##### Go to submission directory #####
cd $SLURM_SUBMIT_DIR

##### Module load #####
module load openmpi/4.1.5rc2/hpcx
export PATH="$HOME/openmpi-4.1.1/bin:/opt/ohpc/pub/apps/uofm/xtb/6.7.0/bin:$PATH"; export LD_LIBRARY_PATH="$HOME/openmpi-4.1.1/lib:$LD_LIBRARY_PATH"
export XTBEXE=/opt/ohpc/pub/apps/uofm/xtb/6.7.0/bin/xtb


# Define the variable RSH_COMMAND for communication 
# between nodes for starting independent calculations 
export RSH_COMMAND="/usr/bin/ssh -x"

##### What is my job ID? ##### 
echo "$SLURM_JOB_ID"

##### Information on list of nodes, n° of nodes, n° of threads, n° of tasks #####
echo "$SLURM_JOB_NODELIST"
echo "$SLURM_NNODES"
echo "$SLURM_NTASKS_PER_NODE"
echo "$SLURM_NTASKS"


##### TMP scratch directory #####
export SCRATCHDIR=/scratch/$USER/$SLURM_JOB_ID/
mkdir $SCRATCHDIR
export TMPDIR=$SCRATCHDIR

cp $SLURM_SUBMIT_DIR/*.inp $SCRATCHDIR/
cp $SLURM_SUBMIT_DIR/*.xyz $SCRATCHDIR/
#cp  $SLURM_SUBMIT_DIR/*.gbw $SCRATCHDIR/
#cp  $SLURM_SUBMIT_DIR/*.xyz $SCRATCHDIR/

cd $SCRATCHDIR

### Executable: Input-Ouput #####
$orcadir/orca $name.inp "--bind-to none" > $SLURM_SUBMIT_DIR/$name.out

rm -rf *.tmp*
cp $SCRATCHDIR/* $SLURM_SUBMIT_DIR/
cd $SLURM_SUBMIT_DIR
rm -rf $SCRATCHDIR

