# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/dwappett/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/dwappett/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/dwappett/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/dwappett/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

###############################
### group aliases/functions ###
###############################

#alias d='pwd'
#alias p='cd ..'
#alias dir='ls -l'
#alias cls='clear'

function mol() { command /home/$USER/newbin/molden -l -S "$@".out >& /dev/null & }
#function qf() { command qstat -f "$@" | command grep exec_host; }
function rwf() { command ssh "$@" 'rm -rf /tmp/r*'; }
function catrwf() { command cat "$@".g98.out | command grep node; }
#function qc() { command qstat -a |grep -v '0 Q ' |grep -c "$@" ;}
#function qc2() { command qstat -a |egrep -v '0 E |0 Q ' |grep -c "$@" ;}
function xyz() { command awk -f ~/newbin/extract-xyz-g03.awk "$@".out ;}
function xyz-freq() { command awk -f ~/newbin/prog-freq-coords.awk "$@" ;}
function xyz-no-freq() { command awk -f ~/bin/extract-xyz-g03-no-freq.awk "$@".out ;}
function zpe() { command pwd; command grep 'Done' "$@".out |command tail -n 1; command grep 'Sum of e' "$@".out ; command grep 'arning' "$@".out  | grep -v 'arning -- This'; command grep "imag" "$@".out ; command grep -m 1 "NBasis" "$@".out ; }
function eigen() { command egrep 'Done|YES| NO |     Eigenvalues ---   -' "$@".out |more;}
function eigen09() { command awk -f ~/bin/eigen.awk 1.out |more;}
function peigen() { command egrep 'extrapolated|YES| NO |     Eigenvalues ---    -' "$@".out |more;}
function scpl() { command scp *.fchk 141.225.147.5:~/"$@"; }
function xyz-mopac() { command awk -f ~/bin/extract-xyz-mopac-msi.awk "$@".out ;}
function mol09() { command awk -f ~/bin/extract-molden-g09-opt.awk "$@".out > geom.mol; command /home/webster/bin/molden -l geom.mol >& /dev/null & }
function cleanfreq() { command awk -f ~/bin/prog-clean-freq.awk "$@".out > freq-clean.out;}
function cleanfreq09() { command awk -f ~/bin/prog-clean-freq-g09.awk "$@".out > freq-clean.out;}
function create-simspec() { command echo "G 20. nm" > input ; command echo "100. 900. 1." >> input ; command grep "\<nm\>" 1.out | awk '{print $9}' | grep -c f >> input ; command grep "Excited State " 1.out | awk '{print $7,$9}' | command sed 's/f=//g' >> input; ~/bin/simspec input; }
function makeonecar() { command make-car.sh ; command cerius-xyz carcoords; command scp carcoords.car 141.225.147.5:"$@"; }
function checknodes() { command mdiag -n -v | awk '{ printf "%-4s  %-10s   %-5s   %-5s   %-20s\n", $1, $2, $3, $11, $13}' | head -n -4 ; }
function xdone() { command egrep 'Step number|NIter=   |NO |YES|Predicted' "$@" ; }
function orcadone() { command egrep 'GEOMETRY OPTIMIZATION CYCLE |     Energy change | RMS gradient | MAX gradient | RMS step | MAX step |FINAL SINGLE POINT ENERGY |FINAL ENERGY EVALUATION AT THE STATIONARY POINT' "$@" ; }

alias hinv='/usr/local/bin/lhinv'
alias xt="xterm -n $hostname -T $hostname -sb -sl 4000 -bg darkgrey -fg black&"
alias o1done="egrep 'Done'"
alias pm3done="egrep 'Energy|NO |YES'"
alias ondone="egrep 'extrapolated|NO |YES'"
alias edone="egrep 'SCF Done|NO |YES|Predicted' *.out"
alias echeck="egrep 'Step number|Done|YES' 1.out | sed 's%SCF Done%\nSCF Done%g' |more"
alias echeckfail="egrep 'Step number|Done|YES' 1-fail-out | sed 's%SCF Done%\nSCF Done%g' |more"
alias mp2done="egrep 'EUMP2|NO |YES|Predicted' *.out"
alias mp3done="egrep 'EUMP3|NO |YES|Predicted' *.out"
alias excdone="egrep 'Total Energy|NO |YES|Predicted' *.out"
alias nwdone="egrep -A3 'Gmax' *.out"
alias fdone="egrep 'SCF Done|NO |YES'"
#alias qu="qstat -u dwappett"
alias qsu="~/bin/qsu.sh"
alias tree="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'"
alias listdir='find ./ -type d |egrep -v $1 | sort'
alias qecheck="egrep 'Total energy|RMS|Gradient  |Displacement'"
alias qedone="egrep 'Total energy|RMS|Gradient  |Displacement|Step '"


######################################
### DAW specific aliases/functions ###
######################################

### for rinrus bio labs ###
alias server='ssh dwappett@rinrus.memphis.edu'

### autocorrect my typos ###
alias qsub='sbatch'
alias sbathc='sbatch'
alias pqs='pwd'
alias ks='ls'
alias mdkir='mkdir'

### make regular tasks/commands faster ###
alias calc='cd /project/dwappett'
alias rinrus='conda activate rinrus'
alias subirc='for i in irc1 irc2; do cp 1 $i; cd $i; sbatch 1; cd ..; done'
alias subircxtb='for i in irc1 irc2; do cp 1 1.fix $i; cd $i; sbatch 1; cd ..; done'
function greq {  # grep freq
  if [ -z "$1" ]; then
    grep -m 1 "Frequencies" 1.out
  else
    grep -m 1 "Frequencies" $1
  fi
}
function pymoll() { # pymol licorice view
  pymol "$@" -d "show_as licorice"
}
function compareoptstrucs() {
  pymol $1/tsopt/*-ts-opt.pdb $1/tsopt/irc*/*-reactant-opt.pdb $1/tsopt/irc*/*-product-opt.pdb -d "show_as licorice"
}
function getfsapt() { # extract fsapt energies from specified fsapt file
  sed -n '/Links 50-50/,$p' $1 | sed -n '/Reduced Analysis/,$p' | awk '$1 == "All"'
}
function switchtotmp() {
  sed -i 's#/scratch/$USER/$SLURM_JOB_ID/#/tmp/$USER/$SLURM_JOB_ID/#; s#export SCRATCHDIR=/tmp/$USER/$SLURM_JOB_ID/#export SCRATCHDIR=/tmp/$USER/$SLURM_JOB_ID/\nmkdir /tmp/$USER#; s#export TMPDIR=/tmp/$USER/$SLURM_JOB_ID/#export TMPDIR=/tmp/$USER/$SLURM_JOB_ID/\ntrap "cp -r ${TMPDIR} /scratch/${USER}/; rm -rf $TMPDIR" EXIT#' $1
  sed -i "s/48:00:00/24:00:00/; s/%4/%1/" $1
}

### queue checking commands ###
# slurm time format variable applies to all slurm squeue/sacct/etc functions but details seem to only exist on sinfo manual page
# see here: https://slurm.schedmd.com/sinfo.html
export SLURM_TIME_FORMAT="%d %b %H:%M"
function qs() { # qs formatted how I like it but if someone else runs it with their username it'll do the old group format that they're used to
  if [ -z "$1" ]; then 
    squeue -u "$USER" -h -t pending,running,suspended -r -o "%P %T" | uniq -c
    #squeue -u "$USER" -t running,pending,suspended -r -o "%16i %10P %12V %8T %12S %.12M %.12l %110Z" --sort="V,S"
    #sacct --state=running,pending,suspended -u "$USER" -X -o jobid%-16,partition%-10,submit%-12,state%-8,start%-12,elapsed%12,timelimit%12,workdir%-110
    sacct --state=running,pending,suspended -u "$USER" -X -o jobid%-14,partition%-4,submit%-12,state%-8,start%-12,elapsed%12,timelimit%12,jobname%-10,workdir%-110
  elif [[ "$1" == "-r" ]]; then
    squeue -u "$USER" -h -t pending,running,suspended -r -o "%P %T" | uniq -c
    squeue -u "$USER" -t running,pending,suspended -r -o "%14i %4P %12V %8T %12S %.12M %.12l %10j %110Z" --sort="i,V,S"
  elif [[ "$1" == "-p" ]]; then
    squeue -u "$USER" -h -t pending,running,suspended -r -o "%P %T" | uniq -c
    squeue -u "$USER" -t running,pending,suspended -o "%14i %4P %12V %8T %12S %.12M %.12l %10j %110Z" --sort="i,V,S"
  elif [[ "$1" == "-d" ]]; then
    squeue -u "$USER" -t running,pending,suspended -o "%14i %8T %.12M %10j %150Z" --sort="i,V,S"
  elif [[ "$1" == "sort" ]]; then
    squeue -u "$USER" -h -t pending,running,suspended -r -o "%P %T" | uniq -c 
    #sacct --state=pending -u "$USER" -X -o jobid%-16,partition%-10,submit%-12,state%-8,start%-12,elapsed%12,timelimit%12,workdir%-110
    #sacct --state=running,suspended -u "$USER" -X -o jobid%-16,partition%-10,submit%-12,state%-8,start%-12,elapsed%12,timelimit%12,workdir%-110 | awk 'NR > 1'
    squeue -u "$USER" -t running,pending,suspended -r -o "%14i %4P %12V %8T %12S %.12M %.12l %10j %110Z" --sort="T,V,S"
  else 
    squeue -u "$1" -h -t pending,running,suspended -r -O "state" | uniq -c
    sacct --state=running,pending,suspended -u "$1" -X -o state,partition,elapsed,timelimit%15,jobid%15,workdir%-120
  fi 
}
# check which jobs have finished in the last hour/day/week. test-qf.sh better because also checks for success
alias qfh='sacct -u "$USER" -X -S now-1hour -E now -s CA,CD,DL,OOM,F,TO -o end%-14,jobid%-16,state%-20,elapsed%12,jobname%-10,workdir%-110 | (sed -u 2q; sort -k1,3)'
alias qfd='sacct -u "$USER" -X -S now-1day -E now -s CA,CD,DL,OOM,F,TO -o end%-14,jobid%-16,state%-20,elapsed%12,jobname%-10,workdir%-110 | (sed -u 2q; sort -k1,3)'
alias qfw='sacct -u "$USER" -X -S now-1week -E now -s CA,CD,DL,OOM,F,TO -o end%-14,jobid%-16,state%-20,elapsed%12,jobname%-10,workdir%-110 | (sed -u 2q; sort -k1,3)'

### defined variables for dirs I need to go to/get stuff from regularly ###
shopt -s direxpand
tcm="/oldhome/tjsntlci/chem/chorismate_sapt"
binrus="/home/dwappett/git/RINRUS/bin" #hehe
aspdc="/project/dwappett/AspDC"
hkmt="/project/dwappett/HKMT"
cm="/project/dwappett/chorismate_mutase"
oldcomt="/hopper/loginMount/tsmmers1/src/COMT/data-compilation"
dehalo="home/jfbchega/chem/dehalo_ACS"
qma="/project/ndyonker/chem/cm-MD-processing/MD-QM/QM-A"
qmb="/project/pssntngr/chem/chorismate_mutase/QM-B/"
qmc="/project/hksasi/chem/chorismate_mutase/QM-C/"
