#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=04:00:00
#SBATCH --partition=acomputeq

source ~/.bashrc
conda activate AmberTools23

################################################################
### script for extracting pdbs, separating into dirs of 1000 ###
### and then submitting second job to run add_chain script   ###
### single/"serial" version: does one cpptraj run            ###
################################################################

SECONDS=0

# make pdbs directory if it doesn't exist yet. if it doesn't exist before running cpptraj, the pdb files won't be created
if [ ! -d "pdbs" ]; then
 mkdir pdbs
fi

# extract pdbs with cpptraj
cpptraj -i extract.in

# rename pdbs with leading zeros so they sort properly, and reorg pdbs dir into pdbs_a, pdbs_b, etc (dirs of 1000 pdbs each)
python ~/git/DeYonker-lab-scripts/MD-analysis/rename.py pdbs

# add chains to everything. sets up a new slurm job in each directory to run everything simultaneously
for i in a b c d e f g h i j k l m n o p q r s t; do
 # checks if dir exists first in case less than 20000 pdbs/not all folders exist
 if [ -d "pdbs_$i" ]; then
  cd pdbs_$i
  ls *.pdb > pdblist.txt
  cp ~/git/DeYonker-lab-scripts/MD-analysis/job_addchain .
  sbatch job_addchain
  cd ..
 fi
done

# this just logs the time
if (( $SECONDS > 3600 )) ; then
    let "hours=SECONDS/3600"
    let "minutes=(SECONDS%3600)/60"
    let "seconds=(SECONDS%3600)%60"
    echo "Completed in $hours hour(s), $minutes minute(s) and $seconds second(s)"
elif (( $SECONDS > 60 )) ; then
    let "minutes=(SECONDS%3600)/60"
    let "seconds=(SECONDS%3600)%60"
    echo "Completed in $minutes minute(s) and $seconds second(s)"
else
    echo "Completed in $SECONDS seconds"
fi
