#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=04:00:00
#SBATCH --partition=acomputeq

source ~/.bashrc
conda activate rinrus

SECONDS=0

# example is for chorismate mutase
# chains specified as: first-res-of-chain/last-res-of-chain/chain-label
# all other res given chain label W for waters.
python $HOME/git/DeYonker-lab-scripts/add_chain.py -list pdblist.txt -chain 1/128/A 129/256/B 257/384/C

if (( $SECONDS > 3600 )) ; then
    let "hours=SECONDS/3600"
    let "minutes=(SECONDS%3600)/60"
    let "seconds=(SECONDS%3600)%60"
    echo "Completed in $hours hour(s), $minutes minute(s) and $seconds second(s)"
elif (( $SECONDS > 60 )) ; then
    let "minutes=(SECONDS%3600)/60"
    let "seconds=(SECONDS%3600)%60"
    echo "Completed in $minutes minute(s) and $seconds second(s)"
else
    echo "Completed in $SECONDS seconds"
fi

