#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=04:00:00
#SBATCH --partition=acomputeq
#SBATCH --array=SETARRAY

source ~/.bash_profile
source ~/.bashrc
conda activate rinrus

##########################################################
### job script for doing check_jobs checks in parallel ###
### use when checking thousands of jobs at once        ###
##########################################################

checkdir=$(head -${SLURM_ARRAY_TASK_ID} SETLISTFILE | tail -1)
check_cm_jobs.sh dir $checkdir
